#!/bin/sh

curl "http://connect.facebook.net/en_US/api/auth/init/ui.methods.js" > connect.js
cat \
  connect.js \
  delegator/delegator.js \
  herstory/herstory.js \
  far/FlashReplace-1.01.js \
  js/*.js \
  | closure > far/min.js
cat streamdiff.css | yuicompressor --type css > far/min.css
rm connect.js
